repositories {
    mavenCentral()
}

jar{
    dependsOn(":modules:core:jar")
    dependsOn(":modules:bot:jar")
}

java {
    withSourcesJar()
}

dependencies {

    testImplementation platform("org.junit:junit-bom:$junit_version")
    testImplementation "org.junit.jupiter:junit-jupiter"
    testImplementation "ch.qos.logback:logback-classic:$logback_version"

    implementation "org.eclipse.jgit:org.eclipse.jgit:$jgit_version"
    implementation "org.eclipse.jetty:jetty-server:$jetty_server_version"
    implementation "org.eclipse.jetty:jetty-servlet:$jetty_servlet_version"


    implementation "net.kyori:adventure-api:4.19.0"
    implementation "net.kyori:adventure-text-serializer-gson:$adventure_api_version"
    implementation "net.kyori:adventure-text-serializer-plain:$adventure_api_version"
    implementation project(":modules:core")
    implementation project(":modules:bot")
}

test {
    useJUnitPlatform()
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
    options.release = JavaLanguageVersion.of("$java_version").asInt()

    sourceCompatibility = JavaLanguageVersion.of("$java_version")
    targetCompatibility = JavaLanguageVersion.of("$java_version")
}