import dex.plugins.outlet.v2.util.ReleaseType
import groovy.text.SimpleTemplateEngine

plugins {
    id 'java'
    id 'maven-publish'
    id 'fabric-loom' version '1.14-SNAPSHOT' apply false
    id 'io.github.dexman545.outlet' version '1.6.1' apply false
    id 'com.modrinth.minotaur' version '2.+' apply false
    id 'com.gradleup.shadow' version '8.3.6' apply false
    id 'xyz.jpenilla.run-paper' version '3.0.2' apply false
    id 'xyz.jpenilla.run-velocity' version '3.0.2' apply false
}

group = "live.qsmc.quipt"
version = "${project_version}-${build_status}.${build_number}"

allprojects {
    group = "live.qsmc.quipt"
    version = "${project_version}-${build_status}.${build_number}"

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'maven-publish'


    java {
        toolchain.languageVersion = JavaLanguageVersion.of(java_version as int)
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }



    dependencies {
        implementation "org.json:json:$json_version"
        implementation "org.eclipse.jgit:org.eclipse.jgit:$jgit_version"
    }
}

configure(subprojects.findAll { it.name == "common" ||  it.name == "velocity" ||  it.name == "paper" ||  it.name == "fabric" }) {
    version = "${project_version}-${build_status}.${build_number}-MC${minecraft_version}"
}


configure(subprojects.findAll { it.name == "paper" || it.name == "fabric" || it.name == "velocity" }) {
    apply plugin: 'com.modrinth.minotaur'
    apply plugin: 'io.github.dexman545.outlet'

    outlet {
        mcVersionRange = supported_minecraft_versions
        allowedReleaseTypes = Set.of(ReleaseType.RELEASE)
    }
    publishing {
        publications {
            create("mavenJava", MavenPublication) {
                artifactId = project.name
                from components.java
            }
        }
    }
    tasks.modrinth.dependsOn(tasks.modrinthSyncBody)
}

java {
    withSourcesJar()
    withJavadocJar()
    toolchain.languageVersion = JavaLanguageVersion.of(java_version as int)
}