import dex.plugins.outlet.v2.util.ReleaseType
import groovy.text.SimpleTemplateEngine

plugins {
    id 'java'
    id 'maven-publish'
    id 'fabric-loom' version '1.14-SNAPSHOT' apply false
    id 'io.github.dexman545.outlet' version '1.6.1' apply false
    id 'com.modrinth.minotaur' version '2.+' apply false
    id 'com.gradleup.shadow' version '8.3.6' apply false
    id 'xyz.jpenilla.run-paper' version '3.0.2' apply false
    id 'xyz.jpenilla.run-velocity' version '3.0.2' apply false
}

group = "live.qsmc"
version = "${project_version}-${build_status}.${build_number}"

allprojects {
    group = "live.qsmc"
    version = "${project_version}-${build_status}.${build_number}"

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'maven-publish'

    archivesBaseName = "quipt-${project.name}"

    java {
        toolchain.languageVersion = JavaLanguageVersion.of(java_version as int)
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    publishing {
        publications {
            create("mavenJava", MavenPublication) {
                artifactId = project.name
                from components.java
            }
        }
        repositories {
            maven {
                url "https://maven.pkg.github.com/Quipt-Minecraft/quipt"
                credentials {
                    username = "QuickScythe"
                    password = System.getenv("PACKAGES_TOKEN")
                }
            }
        }
    }

    dependencies {
        implementation "org.json:json:$json_version"
        implementation "org.eclipse.jgit:org.eclipse.jgit:$jgit_version"
    }
}

configure(subprojects.findAll { it.name == "common" }) {
    version = "${project_version}-${build_status}.${build_number}-MC${minecraft_version}"
}

configure(subprojects.findAll { it.name == "paper" }) {
    apply plugin: 'com.gradleup.shadow'
    apply plugin: 'xyz.jpenilla.run-paper'

    version = "${project_version}-${build_status}.${build_number}-MC${minecraft_version}"

    shadowJar {
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
        mergeServiceFiles()
        exclude 'META-INF/*.SF'
        exclude 'META-INF/*.DSA'
        exclude 'META-INF/*.RSA'
        append 'META-INF/LICENSE'
        append 'META-INF/NOTICE'
    }

    tasks {
        runServer {
            minecraftVersion("${minecraft_version}")
        }
    }
}

configure(subprojects.findAll { it.name == "fabric" }) {
    apply plugin: 'fabric-loom'

    version = "${project_version}-${build_status}.${build_number}-MC${minecraft_version}"

    dependencies {
        minecraft "com.mojang:minecraft:${minecraft_version}"
        mappings "net.fabricmc:yarn:${yarn_mappings}:v2"
        modImplementation "net.fabricmc:fabric-loader:${loader_version}"
        modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    }
}

configure(subprojects.findAll { it.name == "paper" || it.name == "fabric" }) {
    apply plugin: 'com.modrinth.minotaur'
    apply plugin: 'io.github.dexman545.outlet'

    outlet {
        mcVersionRange = supported_minecraft_versions
        allowedReleaseTypes = Set.of(ReleaseType.RELEASE)
    }

    tasks.modrinth.dependsOn(tasks.modrinthSyncBody)

    tasks.register('discord') {
        doLast {
            try {
                def channel = System.getenv("DISCORD_CHANNEL")
                def token = System.getenv("DISCORD_TOKEN")
                URL url = uri("https://discord.com/api/webhooks/$channel/$token").toURL()
                HttpURLConnection connection = (HttpURLConnection) url.openConnection()
                connection.setRequestMethod("POST")
                connection.setRequestProperty("Content-Type", "application/json; utf-8")
                connection.setRequestProperty("Accept", "application/json")
                connection.setDoOutput(true)

                String jsonTemplate = rootProject.file("modrinth.json").text
                def engine = new SimpleTemplateEngine()
                def template = engine.createTemplate(jsonTemplate)
                def binding = [
                        project    : project,
                        rootProject: rootProject,
                        version    : version,
                        modrinth_id: modrinth_id
                ]
                String jsonInputString = template.make(binding).toString()

                try (OutputStream os = connection.getOutputStream()) {
                    byte[] input = jsonInputString.getBytes("utf-8")
                    os.write(input, 0, input.length)
                }

                System.out.println("Discord response: " + connection.getResponseCode())
            } catch (Exception e) {
                e.printStackTrace()
            }
        }
    }
    tasks.modrinth.dependsOn discord
}

java {
    withSourcesJar()
    withJavadocJar()
    toolchain.languageVersion = JavaLanguageVersion.of(java_version as int)
}
