### Build Arguments ###
org.gradle.jvmargs                  =   -Xmx3G -XX:MaxMetaspaceSize=512M -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel                 =   true
org.gradle.caching                  =   true


### Build Info ###
build_status                        =   alpha
build_number                        =   103
project_version                     =   2.0.0
author                              =   QuickScythe

### Argument Info ###
modrinth_id                         =   quipt
minecraft_version                   =   26.1.2
supported_minecraft_versions        =   >=26.1

### Paper Stuff ###
paper_build_number                  =   64
paper_build_channel                 =   stable

### Fabric Stuff ###
loader_version                      =   0.19.2
fabric_version                      =   0.149.1+26.1.2

### Dependency Info ###
java_version                        =   25
json_version                        =   20250517
jgit_version                        =   6.6.1.202309021850-r
hikari_version                      =   4.0.3
jetty_server_version                =   11.0.0
jetty_servlet_version               =   11.0.0
jackson_version                     =   2.18.1
jda_version                         =   5.0.1
jfree_version                       =   1.5.3
spark_version                       =   2.9.3
sql_version                         =   8.0.28
adventure_api_version               =   4.22.0
brigadier_version                   =   1.0.18


### Test Info ###
junit_version                       =   5.10.0
logback_version                     =   1.5.6
