
pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        gradlePluginPortal()
    }
}


rootProject.name = 'quipt'
include ':modules:common'
include ':modules:paper'
include ':modules:fabric'
include ':modules:bot'
include ':modules:core'

