loom {
    mods {
        "quipt" {
            sourceSet sourceSets.main
        }
    }
}

configurations {
    includedDeps.extendsFrom()
}

tasks.register('mergeJar', Jar) {
    from(sourceSets.main.output)
    from(project.project(':modules:core').sourceSets.main.output)
    from(project.project(':modules:common').sourceSets.main.output)
    from(project.project(":modules:bot").sourceSets.main.output)

    configurations.includedDeps.each { dep ->
        from(zipTree(dep)) {
            exclude "META-INF/**"
        }
    }

    archiveClassifier = "dev"
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.build {
    dependsOn('remapJar')
}

dependencies {
    testImplementation platform("org.junit:junit-bom:$junit_version")
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    includedDeps(implementation "org.json:json:$json_version")
    includedDeps(implementation "org.eclipse.jgit:org.eclipse.jgit:$jgit_version")
    includedDeps(implementation "org.eclipse.jetty:jetty-server:$jetty_server_version")
    includedDeps(implementation "org.eclipse.jetty:jetty-servlet:$jetty_servlet_version")
    includedDeps(implementation "com.fasterxml.jackson.core:jackson-core:$jackson_version")
    includedDeps(implementation "com.fasterxml.jackson.core:jackson-databind:$jackson_version")
    includedDeps(implementation "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:$jackson_version")
    includedDeps(implementation "com.fasterxml.jackson.dataformat:jackson-dataformat-xml:$jackson_version")
    includedDeps(implementation "com.fasterxml.jackson.dataformat:jackson-dataformat-toml:$jackson_version")

    modImplementation include("net.kyori:adventure-platform-fabric:6.8.0")

    namedElements(implementation project.project(":modules:core"))
    namedElements(implementation(project.project(":modules:common")))
    namedElements(implementation(project.project(":modules:bot")))
}

modrinth {
    token = System.getenv("MODRINTH_TOKEN")
    changelog = System.getenv("CHANGELOG") ?: rootProject.file("changelog.md").text
    projectId = "${modrinth_id}"
    versionNumber = "${version}"
    versionType = "${build_status}"
    gameVersions = outlet.mcVersions()
    uploadFile = remapJar
    loaders = [project.name]
    syncBodyFrom = rootProject.file("readme.md").text
}

test {
    useJUnitPlatform()
    failOnNoDiscoveredTests = false
}

remapJar {
    input = tasks.mergeJar.archiveFile
    archiveClassifier = ""
}

tasks.generateMetadataFileForMavenJavaPublication {
    dependsOn(tasks.mergeJar)
}

processResources {
    inputs.property "version", project_version
    inputs.property "minecraft_version", minecraft_version
    inputs.property "loader_version", loader_version
    inputs.property "supported_minecraft_versions", supported_minecraft_versions
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": project_version,
                "minecraft_version": minecraft_version,
                "loader_version": loader_version,
                "supported_minecraft_versions": supported_minecraft_versions
    }
}
