
plugins {
    id("java-library")
    id("xyz.jpenilla.run-velocity") version "3.0.2"
    id("com.gradleup.shadow") version "8.3.6"
}

repositories {
    mavenCentral()
    maven {
        url "https://repo.papermc.io/repository/maven-public/"
    }
}

dependencies {
    compileOnly("com.velocitypowered:velocity-api:3.5.0-SNAPSHOT")

    implementation project(":modules:common")
    implementation project(":modules:core")
    implementation "org.json:json:$json_version"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of("${java_version}")
}

tasks {
  runVelocity {
    // Configure the Velocity version for our task.
    // This is the only required configuration besides applying the plugin.
    // Your plugin's jar (or shadowJar if present) will be used automatically.
    velocityVersion("3.5.0-SNAPSHOT")
  }
    shadowJar {
        archiveBaseName.set("quipt-velocity")
        archiveClassifier.set("")
    }
    build {
        dependsOn(shadowJar)
    }
    processResources {
        def pluginProperties = [version: project_version]
        inputs.properties pluginProperties
        filteringCharset 'UTF-8'
        duplicatesStrategy = DuplicatesStrategy.INCLUDE

        from(rootProject.file('gradle.properties'))

        filesMatching('velocity-plugin.json') {
            expand pluginProperties
        }
    }
}
