plugins {
    id "com.gradleup.shadow"
    id "xyz.jpenilla.run-paper"
}

repositories {
    maven {
        name = "papermc-repo"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
    maven {
        name = "sonatype"
        url = "https://oss.sonatype.org/content/groups/public/"
    }
}

dependencies {
    testImplementation platform("org.junit:junit-bom:$junit_version")
    testImplementation "org.junit.jupiter:junit-jupiter"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
    testImplementation "ch.qos.logback:logback-classic:$logback_version"

    compileOnly "io.papermc.paper:paper-api:${minecraft_version}-${paperweight_build}"

    implementation "org.eclipse.jetty:jetty-server:$jetty_server_version"
    implementation "org.eclipse.jetty:jetty-servlet:$jetty_servlet_version"
    implementation "net.kyori:adventure-api:$adventure_api_version"

    implementation project(":modules:common")
    implementation project(":modules:core")
    implementation project(":modules:bot")
}

publishing {
    publications {
        create("paper", MavenPublication) {
            artifactId = project.name
            from components.shadow
        }
    }
}

shadowJar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    mergeServiceFiles()
    exclude 'META-INF/*.SF'
    exclude 'META-INF/*.DSA'
    exclude 'META-INF/*.RSA'
    append 'META-INF/LICENSE'
    append 'META-INF/NOTICE'
}

tasks {
    runServer {
        minecraftVersion("${minecraft_version}")
    }
}

test {
    useJUnitPlatform()
}

processResources {
    def pluginProperties = [minecraft_version: minecraft_version, author: author, name: rootProject.name, project_version: project_version]
    inputs.properties pluginProperties
    filteringCharset 'UTF-8'
    duplicatesStrategy = DuplicatesStrategy.INCLUDE

    from(rootProject.file('gradle.properties'))

    filesMatching('paper-plugin.yml') {
        expand pluginProperties
    }
}

tasks.register('mergeJar', Jar) {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    from(sourceSets.main.output)

    from(project(':modules:core').sourceSets.main.output) {
        exclude "META-INF/**"
    }

    from(project(':modules:common').sourceSets.main.output) {
        exclude "META-INF/**"
    }
}

tasks.generateMetadataFileForMavenJavaPublication {
    dependsOn("mergeJar")
}

tasks.build {
    dependsOn('mergeJar')
}

modrinth {
    token = System.getenv("MODRINTH_TOKEN")
    changelog = System.getenv("CHANGELOG") ?: rootProject.file("changelog.md").text
    projectId = "${modrinth_id}"
    versionNumber = "${version}"
    versionType = "${build_status}"
    gameVersions = outlet.mcVersions()
    uploadFile = jar
    loaders = [project.name]
    syncBodyFrom = rootProject.file("readme.md").text
}
