# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Development

on:
  push:
    branches:
      - '**'
      - '!master'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Setup Permissions
        run: chmod -c 777 gradlew

      - name: Run Tests
        run: ./gradlew test

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "build/results/**/TEST-*.xml"
          output: test-summary.md
        if: always()

      - name: Upload test summary
        uses: actions/upload-artifact@v4
        with:
          name: test-summary
          path: test-summary.md
        if: always()

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: fabric
          path: '${{ github.workspace }}/fabric/build/libs/*.jar'
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: '${{ github.workspace }}/paper/build/libs/*.jar'
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Setup Permissions
        run: chmod -c 777 gradlew
      - name: Publish to Github Packages
        run: |
          echo "BRANCH_NAME is $BRANCH_NAME"
          ./gradlew publish -PisSnapshot=true
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ github.ref_name }}
          PACKAGES_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          DISCORD_CHANNEL: ${{ secrets.DISCORD_CHANNEL }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          SNAPSHOT: "true"